apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "9600"
    port: 9600
    targetPort: 9600
  - name: "5043"
    port: 5043
    targetPort: 5043
  selector:
    io.kompose.service: logstash
status:
  loadBalancer: {}
